config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'welcome/index'

  resources :articles do
    resources :fields do
      resources :cards
    end
  end

  root 'welcome#index'
  

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :field
  mount_uploader :caver_pict, CaverPictUploader
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:field_id])
    @cards = @field.cards.all

  end
  def edit
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:field_id])
    @card = @field.cards.find(params[:id])
  end

  def create
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:field_id])
    @card = @field.cards.create(card_params)
    # redirect_to article_path(@article)
    redirect_to (:back)
  end

  def update
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:field_id])
    @card = @field.cards.find(params[:id])
    if @card.update(card_params)
      redirect_to article_path(@article)+"#field_id_#{@field.id}"
    else
      render 'edit'
    end

  end

  def destroy
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:field_id])
    @card = @field.cards.find(params[:id])
    @card.destroy
    redirect_to (:back)
  end

  private
  def card_params
    params.require(:card).permit( :caption,:caver_pict,:lead,:body,:unicum)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards_for_form.html.haml
.b-cards-for-form
  %table
    - field.cards.each do |card|
      %tr.menu
        %td{:colspan => '3'}
          = render 'cards/menu', card: card
      %tr
        %td
          = image_tag(card.caver_pict_url , size: '50x50')
        %td
          %b #{card.caption}
          %br
          %br
          = card.lead
        %td
          = card.body

app/views/cards/_ccard.html.haml
.b-ccard
  = render 'cards/menu', card: card
  .b-ccard__caver-pict
    = image_tag(card.caver_pict_url , size: '180x180')
  .b-ccard__content
    .b-ccard__caption
      = card.caption
    .b-ccard__lead
      = card.lead
    .b-ccard__body
      = raw card.body

app/views/cards/_cslider.html.haml
.b-cslider{:style => "background-image: url(#{card.caver_pict_url})" }
  = render 'cards/menu', card: card

  .b-cslider__content
    .b-cslider__caption
      %b #{ card.caption}
      = card.lead
    .b-cslider__body
      = card.body

app/views/cards/_form.html.haml
-#%br
-#  %p -------------------FORMA--------------------------------------
-#  = form_for([@article, @field, @field.cards.build]) do |f|
-#    %p
-#      = f.label :caption
-#      = f.text_field :caption
-#    %br
-#    %p
-#      = f.file_field :caver_pict
-#      -#= f.hidden_field :caver_pict_cache
-#    %br
-#    %p
-#      = f.label :lead
-#      = f.text_area :lead
-#    %br
-#    %p
-#      = f.label :body
-#      = f.text_area :body
-#    %br
-#    %p
-#      = f.label :unicum
-#      = f.text_field :unicum
-#    %br
-#
-#    = f.submit(class: 'button_reload')

= simple_form_for [@article, @field, @field.cards.build]  do |f|
  = f.input :caption, input_html: { class: 'input-sm' }
  = f.input :caver_pict, as: :file, input_html: { class: 'btn-sm' }
  = f.input :lead, input_html: { class: 'input-sm' }
  = f.input :body, input_html: { class: 'input-sm' }
  = f.input :unicum, input_html: { class: 'input-sm' }

  = f.button :submit

app/views/cards/_menu.html.haml
- if can? :update, @article
  .b-admin.b-admin_menufield
    = link_to 'Destroy  | ', [card.field.article, card.field, card], method: :delete, data: { confirm: 'Are you sure?' }
    = link_to 'Edit ', edit_article_field_card_path(card.field.article, card.field, card)

app/views/cards/_set_of_cards.html.haml
.b-cards
  - field.cards.each do |card|
    .b-cards_item
      = render 'cards/ccard', card: card

app/views/cards/edit.html.haml
%br
  %p -------------------EDIT CARD--------------------------------------
  = form_for([@article, @field, @card]) do |f|
    %p
      = f.label :caption
      = f.text_field :caption
    %br
    %p
      = f.file_field :caver_pict
    -#= f.hidden_field :caver_pict_cache
    %br
    %p
      = f.label :lead
      = f.text_area :lead
    %br
    %p
      = f.label :body
      = f.text_area :body
    %br
    %p
      = f.label :unicum
      = f.text_field :unicum
    %br

    = f.submit(class: 'button_reload')

app/views/cards/index.html.haml
-# нах ненужно незабыть удалить! and controller!!!!


- @cards.each do |card|
  = render "cards/ccard", card: card

= render 'cards/form'