config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'welcome/index'

  resources :articles do
    resources :fields do
      resources :cards
    end
  end

  root 'welcome#index'
  

end

app/models/field.rb
class Field < ActiveRecord::Base
  FIELDS_NAME = ['caver', 'card','only_text','set_of_cards','slider']
  belongs_to :article
  has_many :cards
  mount_uploader :caver_pict, CaverPictUploader
  default_scope { order(:id) }
  # default_scope { where(teg: true) }
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  def edit
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:id])
  end

  def create
    @article = Article.find(params[:article_id])
    @field = @article.fields.create(field_params)
    redirect_to article_path(@article)+"#field_id_#{@field.id}"
  end

  def update
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:id])
    if @field.update(field_params)
      redirect_to article_path(@article)+"#field_id_#{@field.id}"
    else
      render 'edit'
    end

  end

  def destroy
    @article = Article.find(params[:article_id])
    @field = @article.fields.find(params[:id])
    @field.destroy
    redirect_to article_path(@article)
  end

  private
    def field_params
      params.require(:field).permit( :caption,:caver_pict,:lead,:body,:teg,:unicum)
    end

end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_card.html.haml
= render 'fields/menu', field: field
.l-field{:id => "field_id_#{field.id}"}
  .l-field_card
    .b-field.b-field_card
      .b-field_card__box
        .b-field_card__caver-pict
          = image_tag(field.caver_pict_url , size: '200x200')
          .b_field_card__caption
            = field.caption
          .b-field_card__lead
            = field.lead
        .b-field_card__body
          = field.body

app/views/fields/_caver.html.haml
= render 'fields/menu', field: field
.l-field_caver{:id => "field_id_#{field.id}"}
  .b-field.b-field_caver{:style => "background-image: url(#{field.caver_pict_url})" }
    .b-field_caver__caption
      = field.caption

app/views/fields/_field.html.haml
%h ooooooooooooooooooooooooooooo
%p
  %strong
    = field.caption
%br


- if field.caption.length > 5
  %strong >5

app/views/fields/_form.html.haml
.l-field
  %div{:class => "btn btn-primary btn-lg", 'data-toggle' => "modal", 'data-target' => "#myModal"} Добавить поле

.modal.fade#myModal{'tabindex' => "-1", 'role' => "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{ :type => "button", :class => "close", 'data-dismiss' => "modal", 'aria-hidden' => "true"} &times;
        %h4.modal-title#myModalLabel Форма нового поля
      .modal-body

        = form_for([@article, @article.fields.build]) do |f|
          .form-group
            = f.label :caption
            = f.text_field :caption, class: 'form-control'
          .form-group
            = f.label :teg
            = f.select :teg, Field::FIELDS_NAME
          .form-group
            = f.file_field :caver_pict
            = f.hidden_field :caver_pict_cache
          .form-group
            = f.label :lead
            = f.text_area :lead, class: 'form-control'
          .form-group
            = f.label :body
            = f.text_area :body, class: 'form-control'
          .form-group
            = f.label :unicum
            = f.text_field :unicum, class: 'form-control'


          = f.submit(class: 'button_reload')

app/views/fields/_menu.html.haml
- if can? :update, @article
  .b-admin.b-admin_menufield
    = link_to 'Destroy V', [field.article, field], method: :delete, data: { confirm: 'Are you sure?' }
    = link_to 'Edit', edit_article_field_path(field.article, field)

app/views/fields/_only_text.html.haml
= render 'fields/menu', field: field
.l-field{:id => "field_id_#{field.id}"}
  .l-field_onlytext
    .b-field.b-field_onlytext
      .b-field_onlytext__body
        = field.body

app/views/fields/_set_of_cards.html.haml
= render 'fields/menu', field: field
.l-field.l-field_set-of-cards{:id => "field_id_#{field.id}"}
  = render 'cards/set_of_cards', field: field

app/views/fields/_slider.html.haml
= render 'fields/menu', field: field
.l-field.l-field_slider{:id => "field_id_#{field.id}"}

.swiper-container
  .swiper-wrapper
    - field.cards.each do |card|
      .swiper-slide.swiper-slide_important #{ render 'cards/cslider', card: card if card}

  <!-- If we need pagination -->
  -#.swiper-pagination

  <!-- If we need navigation buttons -->
  .swiper-button-prev
  .swiper-button-next
  <!-- If we need scrollbar -->
  -#.swiper-scrollbar

:javascript
    var mySwiper = new Swiper ('.swiper-container', {
      pagination: '.swiper-pagination',
      slidesPerView: 3,
      //paginationClickable: true,
      spaceBetween: 20,
      freeMode: true,
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
  })

app/views/fields/edit.html.haml
-#%p -------------------Edit--------------------------------------
-#= form_for [@article, @field] do |f|
-#  %p
-#    = f.label :caption
-#    = f.text_field :caption
-#  %br
-#  %p
-#    = f.label :teg
-#    = f.select :teg, Field::FIELDS_NAME
-#  %br
-#  %p
-#    = f.file_field :caver_pict
-#    = f.hidden_field :caver_pict_cache
-#  %br
-#  %p
-#    = f.label :lead
-#    = f.text_area :lead
-#  %br
-#  %p
-#    = f.label :body
-#    = f.text_area :body
-#  %br
-#  %p
-#    = f.label :unicum
-#    = f.text_field :unicum
-#  %br
-#
-#  = f.submit
.col-md-6
  = simple_form_for [@article, @field] do |f|
    = f.input :caption
    = f.input :teg, as: :select, collection: Field::FIELDS_NAME.map{|field| [field, field]}, prompt: nil

    = f.input :caver_pict, as: :file
    = f.input :lead
    = f.input :body
    = f.input :unicum

    = f.button :submit

.col-md-4
  -#%p ====== Cards ======================================
  %br
    = render 'cards/cards_for_form', field: @field

  %br
  -#%p ****** New Card *******
  = render 'cards/form'